# role-heading -> (display role, ledger full name, why)
CAST = {
 'DIRECTIONS': ('Stage directions', 'William Shakespeare', 'Shakespeare reads every heading and stage direction, as in Romeo and Juliet'),
 'CAESAR': ('Julius Caesar', 'Julius Caesar', 'the Romans play themselves'),
 'GHOST': ('Ghost of Caesar', 'Julius Caesar', 'Caesar plays his own ghost'),
 'BRUTUS': ('Marcus Brutus', 'Marcus Junius Brutus', 'the Romans play themselves'),
 'CASSIUS': ('Cassius', 'Gaius Cassius Longinus', 'the Romans play themselves'),
 'ANTONY': ('Mark Antony', 'Mark Antony', 'the Romans play themselves'),
 'OCTAVIUS': ('Octavius Caesar', 'Augustus Caesar', 'Octavius became Augustus — he plays himself'),
 'LEPIDUS': ('Lepidus', 'Lepidus', 'the Romans play themselves'),
 'CICERO': ('Cicero', 'Marcus Tullius Cicero', 'the Romans play themselves'),
 'CASCA': ('Casca', 'Vespasian', 'the play calls Casca “a blunt fellow”; Vespasian is soldierly and blunt'),
 'SOOTHSAYER': ('Soothsayer', 'Nostradamus', 'the ledger’s prophet — “Beware the ides of March”'),
 'ARTEMIDORUS': ('Artemidorus', 'Plutarch', 'a Greek, and the author of the Lives Shakespeare took the play from'),
 'CINNA_POET': ('Cinna the poet', 'Catullus', 'a poet of Caesar’s own day, killed by the mob for his name'),
 'FLAVIUS': ('Flavius', 'Publius Clodius Pulcher', 'a tribune played by a real tribune'),
 'MARULLUS': ('Marullus', 'Sallust', 'a tribune; Sallust was one, and moralizes as Marullus does'),
 'CALPHURNIA': ('Calpurnia', 'Venus', 'Ian, 7 Oct 2026 — Caesar claimed descent from Venus'),
 'PORTIA': ('Portia', 'Zenobia', 'Ian, 7 Oct 2026 — regal and fierce, Cato’s daughter'),
 'CATO': ('Young Cato', 'Cato the Younger', 'his father’s name and his father’s voice'),
 # the conspirators
 'DECIUS': ('Decius Brutus', 'Marcus Licinius Crassus', 'sly and silken — Decius flatters Caesar to the Capitol'),
 'CINNA': ('Cinna', 'Sextus Pompey', 'defiant — a Pompeian against Caesar'),
 'METELLUS': ('Metellus Cimber', 'Pompey', 'grand — he pleads for his banished brother'),
 'TREBONIUS': ('Trebonius', 'Tiberius', 'dour and suspicious — he draws Antony out of the way'),
 'LIGARIUS': ('Ligarius', 'Cincinnatus', 'the sick man who rises from his bed for Brutus, as Cincinnatus from his plough'),
 'PUBLIUS': ('Publius', 'Numa Pompilius', 'the aged senator'),
 'POPILIUS': ('Popilius Lena', 'Marcus Terentius Varro', 'a dry senator'),
 # the household, the camp, the city
 'LUCIUS': ('Lucius', 'Virgil', 'gentle — Brutus’s boy, who plays and falls asleep'),
 'SERVANT': ('Servant', 'Terence', 'Terence was himself a freed slave'),
 'MESSENGER': ('Messenger', 'Terence', 'doubled with the servants'),
 'PINDARUS': ('Pindarus', 'Terence', 'doubled — Cassius’s bondman'),
 'MESSALA': ('Messala', 'Livy', 'Messalla was the patron of Augustan letters'),
 'TITINIUS': ('Titinius', 'Horace', 'Horace fought for Brutus at Philippi'),
 'LUCILIUS': ('Lucilius', 'Suetonius', 'doubled among Brutus’s friends'),
 'VOLUMNIUS': ('Volumnius', 'Cincinnatus', 'doubled with Ligarius'),
 'VARRO': ('Varro', 'Marcus Terentius Varro', 'a Varro plays Varro'),
 'CLAUDIUS': ('Claudius', 'Tiberius', 'Tiberius Claudius — doubled with Trebonius'),
 'STRATO': ('Strato', 'Seneca the Younger', 'the stoic who holds the sword for Brutus'),
 'CLITUS': ('Clitus', 'Lucretius', 'doubled among Brutus’s men'),
 'DARDANIUS': ('Dardanius', 'Cassius Dio', 'doubled among Brutus’s men'),
 'POET': ('A Poet', 'Ovid', 'the poet who breaks into Brutus’s tent'),
 'CARPENTER': ('Carpenter', 'Horatius Cocles', 'a citizen'),
 'COBBLER': ('Cobbler', 'Plautus', 'bawdy and boisterous — every line a pun'),
 'FIRST CITIZEN': ('First Citizen', 'Spartacus', 'the crowd: rebellious and rallying'),
 'SECOND CITIZEN': ('Second Citizen', 'Plautus', 'doubled with the Cobbler'),
 'THIRD CITIZEN': ('Third Citizen', 'Horatius Cocles', 'doubled with the Carpenter'),
 'FOURTH CITIZEN': ('Fourth Citizen', 'Remus', 'quick and restless'),
 'CITIZENS': ('Citizens', 'Spartacus', 'the crowd speaks as one through its loudest'),
 'FIRST SOLDIER': ('First Soldier', 'Horatius Cocles', 'doubled'),
 'SECOND SOLDIER': ('Second Soldier', 'Remus', 'doubled'),
 'THIRD SOLDIER': ('Third Soldier', 'Spartacus', 'doubled'),
}
